# Generated by Django 4.2.3 on 2023-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="prompt",
            field=models.TextField(max_length=255),
        ),
    ]
