# Generated by Django 4.2.3 on 2023-07-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_conversation_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="chat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="chatbot.chat",
            ),
            preserve_default=False,
        ),
    ]
